const PREFIX = '@SHOWUP/';

export const ADD_ALERT_NOTIFICATION = `${PREFIX}ADD_ALERT_NOTIFICATION`;
export const ADD_ERROR_NOTIFICATION = `${PREFIX}ADD_ERROR_NOTIFICATION`;
export const CLEAR_NOTIFICATION = `${PREFIX}CLEAR_NOTIFICATION`;
